### ISSUE TITLE
unstable script: manifests/e2e/create-cert.sh

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#1075]
## Bug Report

it may fail in e2e, example logs:

```
[2019-10-30T02:35:48.632Z] I1030 02:35:48.530882       1 actions.go:433] /manifests/e2e/create-cert.sh --namespace pingcap

[2019-10-30T02:36:06.671Z] panic: failed to create cert: exit status 1, Generating RSA private key, 2048 bit long modulus

[2019-10-30T02:36:06.671Z] .........................+++++

[2019-10-30T02:36:06.671Z] ..................................................................................................................................................................+++++

[2019-10-30T02:36:06.671Z] e is 65537 (0x10001)

[2019-10-30T02:36:06.671Z] certificatesigningrequest.certificates.k8s.io/admission-controller-svc.pingcap created

[2019-10-30T02:36:06.671Z] NAME                               AGE   REQUESTOR                                                   CONDITION

[2019-10-30T02:36:06.671Z] admission-controller-svc.pingcap   0s    system:serviceaccount:tidb-operator-e2e:tidb-operator-e2e   Pending

[2019-10-30T02:36:06.671Z] certificatesigningrequest.certificates.k8s.io/admission-controller-svc.pingcap approved

[2019-10-30T02:36:06.671Z] ERROR: After approving csr admission-controller-svc.pingcap, the signed certificate did not appear on the resource. Giving up after 10 attempts.

[2019-10-30T02:36:06.671Z] 

[2019-10-30T02:36:06.671Z] 

[2019-10-30T02:36:06.671Z] goroutine 1 [running]:

[2019-10-30T02:36:06.671Z] github.com/pingcap/tidb-operator/tests/slack.NotifyAndPanic(0x18b3aa0, 0xc000705d40)

[2019-10-30T02:36:06.671Z] 	/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/slack/slack.go:156 +0x271

[2019-10-30T02:36:06.671Z] github.com/pingcap/tidb-operator/tests.(*operatorActions).DeployOperatorOrDie(0xc0004ea360, 0xc000184000)

[2019-10-30T02:36:06.671Z] 	/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/actions.go:463 +0x5c

[2019-10-30T02:36:06.671Z] main.main()

[2019-10-30T02:36:06.671Z] 	/home/jenkins/agent/workspace/operator_ghpr_e2e_test_kind/go/src/github.com/pingcap/tidb-operator/tests/cmd/e2e/main.go:71 +0x6db

[2019-10-30T02:36:09.188Z] ++ kubectl get po tidb-operator-e2e -n tidb-operator-e2e '-ojsonpath={.status.phase}'

[2019-10-30T02:36:09.188Z] + status=Failed

[2019-10-30T02:36:09.188Z] + [[ Failed == Succeeded ]]

[2019-10-30T02:36:09.188Z] + [[ Failed == Failed ]]

[2019-10-30T02:36:09.188Z] + exit 1

[2019-10-30T02:36:09.188Z] + echo '############ end of e2e test running on the cluster: kind4 ############'
```

**Comment by cofyc** [comment]
it does not happen anymore, I guess it's because of unstable environment.
