### ISSUE TITLE
./hack/aa-codegen.sh fails to generate code

### ISSUE THREAD

**Issue by cofyc** [pingcap/tidb-operator#1456]
```
$ ./hack/aa-codegen.sh 
Generating api registries
panic: Missing apis package.

goroutine 1 [running]:
sigs.k8s.io/apiserver-builder-alpha/cmd/apiregister-gen/generators.(*APIsBuilder).ParseDomain(0xc000210600)
	/data/go/pkg/mod/sigs.k8s.io/apiserver-builder-alpha/cmd@v0.0.0-20191113095113-4493943d2568/apiregister-gen/generators/parser.go:534 +0x151
sigs.k8s.io/apiserver-builder-alpha/cmd/apiregister-gen/generators.NewAPIsBuilder(0xc0001f2720, 0xc0000f1900, 0x4ce9d9)
	/data/go/pkg/mod/sigs.k8s.io/apiserver-builder-alpha/cmd@v0.0.0-20191113095113-4493943d2568/apiregister-gen/generators/parser.go:186 +0x6c
sigs.k8s.io/apiserver-builder-alpha/cmd/apiregister-gen/generators.(*Gen).Packages(0xc00000e500, 0xc0001f2720, 0xc0000f1900, 0x3000107, 0x0, 0xffffffffffffffff)
	/data/go/pkg/mod/sigs.k8s.io/apiserver-builder-alpha/cmd@v0.0.0-20191113095113-4493943d2568/apiregister-gen/generators/package.go:89 +0x76
k8s.io/gengo/args.(*GeneratorArgs).Execute(0xc0000f1900, 0xc0000d5da0, 0x7bd089, 0x6, 0xc0000d5d90, 0xc00001e140, 0x0)
	/data/go/pkg/mod/k8s.io/gengo@v0.0.0-20190907103519-ebc107f98eab/args/args.go:203 +0x1a8
sigs.k8s.io/apiserver-builder-alpha/cmd/apiregister-gen/generators.(*Gen).Execute(0xc00000e500, 0xc0000f1900, 0x0, 0x0)
	/data/go/pkg/mod/sigs.k8s.io/apiserver-builder-alpha/cmd@v0.0.0-20191113095113-4493943d2568/apiregister-gen/generators/package.go:42 +0x1c2
main.main()
	/data/go/pkg/mod/sigs.k8s.io/apiserver-builder-alpha/cmd@v0.0.0-20191113095113-4493943d2568/apiregister-gen/main.go:44 +0xc5
```

**Comment by aylei** [comment]
This is expected, because there is actually no api package now

**Comment by cofyc** [comment]
got it
