### ISSUE TITLE
tidb-operator panic

### ISSUE THREAD

**Issue by zjj2wry** [pingcap/tidb-operator#3354]
## Bug Report

```log
E1005 14:16:31.376645       1 tidbcluster_control.go:82] failed to update TidbCluster: [tidb1313117082807701504/db], error: Put https://100.64.0.1:443/apis/pingcap.com/v1alpha1/namespaces/tidb1313117082807701504/tidbclusters/db: read tcp 100.96.1.15:56062->100.64.0.1:443: read: connection reset by peer
E1005 14:16:31.376736       1 tidb_cluster_controller.go:304] TidbCluster: tidb1313117082807701504/db, sync failed Put https://100.64.0.1:443/apis/pingcap.com/v1alpha1/namespaces/tidb1313117082807701504/tidbclusters/db: read tcp 100.96.1.15:56062->100.64.0.1:443: read: connection reset by peer, requeuing
W1005 14:16:31.857122       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1.Deployment ended with: too old resource version: 2775182 (2776472)
W1005 14:16:31.857337       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1.PersistentVolumeClaim ended with: too old resource version: 2774169 (2776468)
W1005 14:16:31.857122       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1.Pod ended with: too old resource version: 2775179 (2776468)
W1005 14:16:31.858947       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1beta1.Ingress ended with: too old resource version: 2768045 (2776470)
W1005 14:16:31.859260       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1.Job ended with: too old resource version: 2775084 (2776470)
W1005 14:16:31.859074       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1.Service ended with: too old resource version: 2774153 (2776469)
W1005 14:16:31.859142       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1.StorageClass ended with: too old resource version: 2768048 (2776472)
W1005 14:16:31.859196       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1.PersistentVolume ended with: too old resource version: 2774172 (2776468)
W1005 14:16:31.885424       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1alpha1.TidbMonitor ended with: too old resource version: 2768687 (2777068)
W1005 14:16:32.647723       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1alpha1.TidbCluster ended with: too old resource version: 2777025 (2777075)
W1005 14:16:32.707480       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1alpha1.BackupSchedule ended with: too old resource version: 2768686 (2777078)
W1005 14:16:32.793764       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1alpha1.Restore ended with: too old resource version: 2775073 (2777079)
W1005 14:16:32.831275       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1alpha1.Backup ended with: too old resource version: 2768687 (2777079)
W1005 14:16:32.870357       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1alpha1.TidbClusterAutoScaler ended with: too old resource version: 2768688 (2777079)
W1005 14:16:32.902669       1 reflector.go:299] k8s.io/client-go@v0.0.0/tools/cache/reflector.go:96: watch of *v1alpha1.TidbInitializer ended with: too old resource version: 2768687 (2777079)
E1005 14:16:32.990129       1 runtime.go:76] Observed a panic: unreachable
goroutine 20436 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x19c8de0, 0x2085870)
	k8s.io/apimachinery@v0.0.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	k8s.io/apimachinery@v0.0.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x19c8de0, 0x2085870)
	runtime/panic.go:679 +0x1b2
github.com/pingcap/advanced-statefulset/client/apis/apps/v1/helper.(*hijackWatch).receive(0xc0009aa330)
	github.com/pingcap/advanced-statefulset/client@v1.16.0/apis/apps/v1/helper/hijack.go:165 +0x2c5
created by github.com/pingcap/advanced-statefulset/client/apis/apps/v1/helper.newHijackWatch
	github.com/pingcap/advanced-statefulset/client@v1.16.0/apis/apps/v1/helper/hijack.go:140 +0x9f
panic: unreachable [recovered]
	panic: unreachable

goroutine 20436 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	k8s.io/apimachinery@v0.0.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x19c8de0, 0x2085870)
	runtime/panic.go:679 +0x1b2
github.com/pingcap/advanced-statefulset/client/apis/apps/v1/helper.(*hijackWatch).receive(0xc0009aa330)
	github.com/pingcap/advanced-statefulset/client@v1.16.0/apis/apps/v1/helper/hijack.go:165 +0x2c5
created by github.com/pingcap/advanced-statefulset/client/apis/apps/v1/helper.newHijackWatch
	github.com/pingcap/advanced-statefulset/client@v1.16.0/apis/apps/v1/helper/hijack.go:140 +0x9f
```

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

v1.1.1

**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by DanielZhangQD** [comment]
@zjj2wry 
1. Is this issue hit repeatedly? Do you know how to reproduce this issue?
2. `failed to update TidbCluster: [tidb1313117082807701504/db], error: Put https://100.64.0.1:443/apis/pingcap.com/v1alpha1/namespaces/tidb1313117082807701504/tidbclusters/db: read tcp 100.96.1.15:56062->100.64.0.1:443: read: connection reset by peer` Is there something wrong with the kube-apiserver at that time?
3. What happened with the cluster? Is new asts being created?

Any more information that you think may help reproduce this issue or identify the root cause please help update here.
Thanks!

**Comment by zjj2wry** [comment]
can not reproduce it. maybe cause by network error
