### ISSUE TITLE
Backup & Restore with BR fail

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb-operator#3681]
## Bug Report

**What version of Kubernetes are you using?**

**What version of TiDB Operator are you using?**

v1.1.9
**What storage classes exist in the Kubernetes cluster and what are used for PD/TiKV pods?**

**What's the status of the TiDB cluster pods?**

**What did you do?**

Backup with BR with TiDB v4.0.9 without configuring `spec.from`, and TLS is enabled and `${cluster_name}-tidb-client-secret"` is not created.
Restore with BR with TiDB v4.0.9 without configuring `spec.to`, and TLS is enabled.
**What did you expect to see?**
Backup & Restore succeeds
**What did you see instead?**
Error with backup:
```
MountVolume.SetUp failed for volume "tidb-client-tls" : secret "${cluster_name}-tidb-client-secret" not found
```

Error with restore：
```
E0105 15:22:29.000946       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 756 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1a9d9c0, 0x2fa4210)
	k8s.io/apimachinery@v0.0.0/pkg/util/runtime/runtime.go:74 +0xa3
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	k8s.io/apimachinery@v0.0.0/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1a9d9c0, 0x2fa4210)
	runtime/panic.go:679 +0x1b2
github.com/pingcap/tidb-operator/pkg/backup/restore.(*restoreManager).makeRestoreJob(0xc000692f00, 0xc0005f4f00, 0x1d29edb, 0x8, 0x20f2ca0, 0xc000123360, 0x1a)
	github.com/pingcap/tidb-operator@/pkg/backup/restore/restore_manager.go:364 +0xc55
github.com/pingcap/tidb-operator/pkg/backup/restore.(*restoreManager).syncRestoreJob(0xc000692f00, 0xc0005f4f00, 0x1d28655, 0x7)
	github.com/pingcap/tidb-operator@/pkg/backup/restore/restore_manager.go:130 +0x7ea
github.com/pingcap/tidb-operator/pkg/backup/restore.(*restoreManager).Sync(0xc000692f00, 0xc0005f4f00, 0x1d2ac3b, 0x8)
	github.com/pingcap/tidb-operator@/pkg/backup/restore/restore_manager.go:48 +0x35
github.com/pingcap/tidb-operator/pkg/controller/restore.(*defaultRestoreControl).UpdateRestore(0xc00096a6b0, 0xc0005f4f00, 0x0, 0x0)
	github.com/pingcap/tidb-operator@/pkg/controller/restore/restore_control.go:49 +0xda
github.com/pingcap/tidb-operator/pkg/controller/restore.(*Controller).syncRestore(...)
	github.com/pingcap/tidb-operator@/pkg/controller/restore/restore_controller.go:133
github.com/pingcap/tidb-operator/pkg/controller/restore.(*Controller).sync(0xc000541a70, 0xc000f739c0, 0x16, 0x0, 0x0)
	github.com/pingcap/tidb-operator@/pkg/controller/restore/restore_controller.go:129 +0x1f0
github.com/pingcap/tidb-operator/pkg/controller/restore.(*Controller).processNextWorkItem(0xc000541a70, 0x0)
	github.com/pingcap/tidb-operator@/pkg/controller/restore/restore_controller.go:93 +0x106
github.com/pingcap/tidb-operator/pkg/controller/restore.(*Controller).worker(0xc000541a70)
	github.com/pingcap/tidb-operator@/pkg/controller/restore/restore_controller.go:81 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00144c100)
	k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00144c100, 0x3b9aca00, 0x0, 0x1, 0xc0009e0180)
	k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00144c100, 0x3b9aca00, 0xc0009e0180)
	k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:88 +0x4d
created by github.com/pingcap/tidb-operator/pkg/controller/restore.(*Controller).Run
	github.com/pingcap/tidb-operator@/pkg/controller/restore/restore_controller.go:73 +0x1d9
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x16ebf25]
goroutine 756 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	k8s.io/apimachinery@v0.0.0/pkg/util/runtime/runtime.go:55 +0x105
panic(0x1a9d9c0, 0x2fa4210)
	runtime/panic.go:679 +0x1b2
github.com/pingcap/tidb-operator/pkg/backup/restore.(*restoreManager).makeRestoreJob(0xc000692f00, 0xc0005f4f00, 0x1d29edb, 0x8, 0x20f2ca0, 0xc000123360, 0x1a)
	github.com/pingcap/tidb-operator@/pkg/backup/restore/restore_manager.go:364 +0xc55
github.com/pingcap/tidb-operator/pkg/backup/restore.(*restoreManager).syncRestoreJob(0xc000692f00, 0xc0005f4f00, 0x1d28655, 0x7)
	github.com/pingcap/tidb-operator@/pkg/backup/restore/restore_manager.go:130 +0x7ea
github.com/pingcap/tidb-operator/pkg/backup/restore.(*restoreManager).Sync(0xc000692f00, 0xc0005f4f00, 0x1d2ac3b, 0x8)
	github.com/pingcap/tidb-operator@/pkg/backup/restore/restore_manager.go:48 +0x35
github.com/pingcap/tidb-operator/pkg/controller/restore.(*defaultRestoreControl).UpdateRestore(0xc00096a6b0, 0xc0005f4f00, 0x0, 0x0)
	github.com/pingcap/tidb-operator@/pkg/controller/restore/restore_control.go:49 +0xda
github.com/pingcap/tidb-operator/pkg/controller/restore.(*Controller).syncRestore(...)
	github.com/pingcap/tidb-operator@/pkg/controller/restore/restore_controller.go:133
github.com/pingcap/tidb-operator/pkg/controller/restore.(*Controller).sync(0xc000541a70, 0xc000f739c0, 0x16, 0x0, 0x0)
	github.com/pingcap/tidb-operator@/pkg/controller/restore/restore_controller.go:129 +0x1f0
github.com/pingcap/tidb-operator/pkg/controller/restore.(*Controller).processNextWorkItem(0xc000541a70, 0x0)
	github.com/pingcap/tidb-operator@/pkg/controller/restore/restore_controller.go:93 +0x106
github.com/pingcap/tidb-operator/pkg/controller/restore.(*Controller).worker(0xc000541a70)
	github.com/pingcap/tidb-operator@/pkg/controller/restore/restore_controller.go:81 +0x2b
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00144c100)
	k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:152 +0x5e
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00144c100, 0x3b9aca00, 0x0, 0x1, 0xc0009e0180)
	k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(0xc00144c100, 0x3b9aca00, 0xc0009e0180)
	k8s.io/apimachinery@v0.0.0/pkg/util/wait/wait.go:88 +0x4d
created by github.com/pingcap/tidb-operator/pkg/controller/restore.(*Controller).Run
	github.com/pingcap/tidb-operator@/pkg/controller/restore/restore_controller.go:73 +0x1d9
```

**Comment by DanielZhangQD** [comment]
Test cases:

1. Create a TiDB cluster without TLS enabled
2. Create a TiDB cluster with TLS among the cluster components and TLS between the TiDB client and TiDB server enabled, DO NOT create `${cluster_name}-tidb-client-secret`.
3. Backup with BR without configuring `spec.from` for the above two clusters
4. Restore with BR without configuring `spec.to` for the above two clusters
