### ISSUE TITLE
the tidb-controller-manager is not available when stop and start one etcd instance

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb-operator#558]
In the stability tests env. The case crashed:

```
I0605 10:12:14.145949       1 fault.go:356] stop etcd 172.16.4.149 successfully
I0605 10:15:14.146200       1 failover.go:439] check k8s/operator/tidbCluster status when one etcd down
I0605 10:15:25.251964       1 fault.go:356] start etcd 172.16.4.149 successfully
I0605 10:15:35.315255       1 blockwriter.go:258] [block_writer] stoping...
I0605 10:15:35.319872       1 blockwriter.go:163] run stopped
I0605 10:15:35.325204       1 blockwriter.go:163] run stopped
I0605 10:15:35.325238       1 blockwriter.go:163] run stopped
I0605 10:15:35.325665       1 blockwriter.go:163] run stopped
I0605 10:15:35.325691       1 blockwriter.go:163] run stopped
I0605 10:15:35.329139       1 blockwriter.go:163] run stopped
I0605 10:15:35.330200       1 blockwriter.go:163] run stopped
I0605 10:15:35.330660       1 blockwriter.go:163] run stopped
I0605 10:15:35.354921       1 blockwriter.go:99] [block_writer] [stability-cluster2] [action: generate Query] stopped
I0605 10:15:35.354958       1 blockwriter.go:225] [block_writer] [stability-cluster2] stopped
E0605 10:15:45.253275       1 runtime.go:69] Observed a panic: &errors.errorString{s:"the tidb-controller-manager is not available"} (the tidb-controller-manager is not available)
/Users/changjunchang/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181128191346-49ce2735e507/pkg/util/runtime/runtime.go:76
/Users/changjunchang/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181128191346-49ce2735e507/pkg/util/runtime/runtime.go:65
/Users/changjunchang/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181128191346-49ce2735e507/pkg/util/runtime/runtime.go:51
/usr/local/Cellar/go/1.12.1/libexec/src/runtime/panic.go:522
/Users/changjunchang/go/src/github.com/pingcap/tidb-operator/tests/slack/slack.go:154
/Users/changjunchang/go/src/github.com/pingcap/tidb-operator/tests/util.go:40
/Users/changjunchang/go/src/github.com/pingcap/tidb-operator/tests/failover.go:440
/Users/changjunchang/go/src/github.com/pingcap/tidb-operator/tests/cmd/stability/main.go:338
/Users/changjunchang/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181128191346-49ce2735e507/pkg/util/wait/wait.go:133
/Users/changjunchang/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181128191346-49ce2735e507/pkg/util/wait/wait.go:134
/Users/changjunchang/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181128191346-49ce2735e507/pkg/util/wait/wait.go:88
/Users/changjunchang/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181128191346-49ce2735e507/pkg/util/wait/wait.go:79
/Users/changjunchang/go/src/github.com/pingcap/tidb-operator/tests/cmd/stability/main.go:65
/usr/local/Cellar/go/1.12.1/libexec/src/runtime/proc.go:200
/usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:1337
panic: the tidb-controller-manager is not available [recovered]
	panic: the tidb-controller-manager is not available

goroutine 1 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/Users/changjunchang/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181128191346-49ce2735e507/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1694c20, 0xc0009f0700)
	/usr/local/Cellar/go/1.12.1/libexec/src/runtime/panic.go:522 +0x1b5
github.com/pingcap/tidb-operator/tests/slack.NotifyAndPanic(0x1b39e40, 0xc0009f0700)
	/Users/changjunchang/go/src/github.com/pingcap/tidb-operator/tests/slack/slack.go:154 +0x194
github.com/pingcap/tidb-operator/tests.KeepOrDie(0xb2d05e00, 0x8bb2c97000, 0xc00c1d9ba0)
	/Users/changjunchang/go/src/github.com/pingcap/tidb-operator/tests/util.go:40 +0xa8
github.com/pingcap/tidb-operator/tests.(*operatorActions).CheckOneEtcdDownOrDie(0xc0000ce900, 0xc00b85bee0, 0xc018710160, 0x3, 0x3, 0xc0000466d0, 0xc)
	/Users/changjunchang/go/src/github.com/pingcap/tidb-operator/tests/failover.go:440 +0xe3
main.run()
	/Users/changjunchang/go/src/github.com/pingcap/tidb-operator/tests/cmd/stability/main.go:338 +0x34db
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0x1973950)
	/Users/changjunchang/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181128191346-49ce2735e507/pkg/util/wait/wait.go:133 +0x54
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x1973950, 0x45d964b800, 0x0, 0x1b3c901, 0xc00017e060)
	/Users/changjunchang/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181128191346-49ce2735e507/pkg/util/wait/wait.go:134 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
	/Users/changjunchang/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181128191346-49ce2735e507/pkg/util/wait/wait.go:88
k8s.io/apimachinery/pkg/util/wait.Forever(...)
	/Users/changjunchang/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20181128191346-49ce2735e507/pkg/util/wait/wait.go:79
main.main()
	/Users/changjunchang/go/src/github.com/pingcap/tidb-operator/tests/cmd/stability/main.go:65 +0x1a8
```

**Comment by weekface** [comment]
didn't happen again.
